### ISSUE TITLE
Unable to commit properly

### ISSUE THREAD

**Issue by shmabry** [FlubDubStubs/PurpleAmerica#14]
![purple america head](https://cloud.githubusercontent.com/assets/18354451/15299668/62b55d6e-1b73-11e6-93d7-37522ddf7a12.PNG)

I keep getting this error when I try to commit. I looked it up on Stack Overflow but I don't understand what is says. It also looks like it needs to be in Terminal. Nobody in class knows what this error is either. @cmneville

**Comment by cmneville** [comment]
I believe I can fix this.  I will have to take a look at it.  I looked at the stack overflow and I understand what the problem is, I will just need to play with netbeans to figure out what I need to do to fix it.  @hcps-mabrysh if you come see me at some point I can take a look.  If you can't come see me, we will have to wait until Monday when I see 6th block.

**Comment by cmneville** [comment]
Actually, maybe I can help clear up the problem and you can fix it yourself.  Let me explain what the issue is.  

If you recall from my lecture on Git, HEAD is an object that holds a reference to the current branch you are working on.  This is illustrated in this image
![head-to-master](https://cloud.githubusercontent.com/assets/17484863/15394971/c99da694-1da3-11e6-8724-29d8b998a6b2.png)

Somehow, you ended up with a situation where that reference is pointing directly to a commit instead of pointing to a branch.  This means that your changes are not being tracked on the master branch and Git knows this is probably not what you want and so it is warning you.

Here is how I would try to fix this in Netbeans:
1. In the Project Pane (the area on the left side with all the expandable projects) right click on your Purple America project and go down to Git.  Select the "branch/tag" menu and select "Create branch".  
2. In the popup window, name the branch "temp".  Click create.
3. Right click the project, go to the Git menu, then the "Repository" menu then select Repository Browser.  This will open a window in the bottom section of the Netbeans window that shows all your repositories.  Go to the Purple America repo, expand it if necessary, then expand "Branches", then expand "Local".  Here you should see two things, "master" and "temp" and "temp" should be boldfaced.  If this is the case then great!
4. Go back to the project pane, right click your Purple America project, go to Git, go to the "branch/tags" menu and select "Switch to master".  Now if you look at the Repository browser you just opened up in step 3, master should be boldfaced instead of temp.
5.  In the Repository browser window, right click the  "temp" branch and then select "Merge Revision".  This will open a popup menu.  In the Revision field, ensure that temp is showing, if not, put it in.  Then click Merge.  

This should fix the problem.  Let me know if it works and if not I will probably have to play with it
